<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Canciones [
        <!ELEMENT Canciones (Cancion)*>
        <!ELEMENT Cancion (Duracion|Anio|Titulo|Compositores|Productores|Sello|Artistas)*>
        <!ELEMENT Duracion (#PCDATA)>
        <!ELEMENT Anio (#PCDATA)>
        <!ELEMENT Titulo (#PCDATA)>
        <!ELEMENT Compositores (Compositor)*>
        <!ELEMENT Compositor (Nombre|Apellidos)*>
        <!ELEMENT Nombre (#PCDATA)>
        <!ELEMENT Apellidos (#PCDATA)>
        <!ELEMENT Productores (Productor)*>
        <!ELEMENT Productor (Nombre)*>
        <!ELEMENT Sello (#PCDATA)>
        <!ELEMENT Artistas (Artista)*>
        <!ELEMENT Artista (Nombre|Apellido)*>
        <!ELEMENT Apellido (#PCDATA)>
        ]>
<Canciones>
    <Cancion>
        <Duracion>6.04</Duracion>
        <Anio>2017</Anio>
        <Titulo>Si tu supieras compa√±ero</Titulo>
        <Compositores>
            <Compositor>
                <Nombre>Rosalia</Nombre>
                <Apellidos>Vila Torbella</Apellidos>
            </Compositor>
        </Compositores>
        <Productores>
            <Productor>
                <Nombre>Raul Refree</Nombre>
            </Productor>
        </Productores>
        <Sello>Universal Music Spain S.L.</Sello>
        <Artistas>
            <Artista>
                <Nombre>Rosalia</Nombre>
            </Artista>
        </Artistas>
    </Cancion>
    <Cancion>
        <Duracion>2:30</Duracion>
        <Anio>2018</Anio>
        <Titulo>MALAMENTE</Titulo>
        <Compositores>
            <Compositor>
                <Nombre>Pablo</Nombre>
                <Apellidos>Diaz-Reixa</Apellidos>
            </Compositor>
            <Compositor>
                <Nombre>Rosalia</Nombre>
                <Apellidos>Vila</Apellidos>
            </Compositor>
            <Compositor>
                <Nombre>Anton</Nombre>
                <Apellidos>Alavrez Alfaro</Apellidos>
            </Compositor>
        </Compositores>
        <Productores>
            <Productor>
                <Nombre>Rosalia</Nombre>
            </Productor>
        </Productores>
        <Sello>Columbia, Universal Music Publishing</Sello>
        <Artistas>
            <Artista>
                <Nombre>Rosalia</Nombre>
            </Artista>
        </Artistas>
    </Cancion>
    <Cancion>
        <Duracion>2:23</Duracion>
        <Anio>2020</Anio>
        <Titulo>Dolerme</Titulo>
        <Compositores>
            <Compositor>
                <Nombre>Frank</Nombre>
                <Apellidos>Dukees</Apellidos>
            </Compositor>
            <Compositor>
                <Nombre>Matthew</Nombre>
                <Apellidos>Tavares</Apellidos>
            </Compositor>
        </Compositores>
        <Productores>
            <Productor>
                <Nombre>Frank</Nombre>
            </Productor>
        </Productores>
        <Sello>Columbia, Sony Music Publishing</Sello>
        <Artistas>
            <Artista>
                <Nombre>Rosalia</Nombre>
            </Artista>
        </Artistas>
    </Cancion>
</Canciones>